---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/.github/actions/version"
    schedule:
      interval: "daily"

#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "weekly"