name: Release To Version
description: Get the version information from github release and save the version information to the github repository.

inputs:
  debug:
    description: 是否输出调试信息
    default: "false"
  repository:
    description: 需要检查的仓库
    default: ""
    required: true
  output_file:
    description: 用于指定版本信息的输出文件
    default: "versions.json"
    required: true

outputs:
  version:
    description: 最新的版本号
  update_content:
    description: 最新版本更新内容

runs:
  using: docker
  image: "Dockerfile"
  args:
    - ${{ inputs.debug }}