name: "测试docker workflows是否正确执行"
run-name: "测试docker workflows是否正确执行 | ${{ github.event_name }} 调试模式 - ${{ inputs.debug || github.event_name == 'push' }}"
on:
  release:
    types:
      - published
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 是否开启调试模式
        default: true
      repository:
        type: string
        default: ""
        description: 需要获取信息的仓库，必须为公开类型的仓库
      branch:
        type: string
        default: "main"
        description: 需要提交版本信息的分支
      jest:
        type: boolean
        description: 是否启用测试
        default: false

env:
  DEBUG: ${{ inputs.debug || github.event_name == 'push' }}
  REPOSITORY: ${{ inputs.repository || github.repository }}
  BRANCH: ${{ inputs.branch || 'main' }}

permissions:
  contents: write

jobs:
  jest:
    if: ${{ inputs.jest || github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        uses: actions/checkout@v4
        with:
          repository: m8test/release-to-version
      - name: 安装依赖并启动 jest
        working-directory: ./.github/actions/version
        run: |
          npm install
          npm run test
  version:
    runs-on: ubuntu-latest
    steps:
      - name: 下载仓库代码
        uses: actions/checkout@v4
      - name: 输出github工作目录
        id: workspace
        run: |
          echo "workspace=$GITHUB_WORKSPACE" >> "$GITHUB_OUTPUT"
      - name: 使用 actions
        id: release
        uses: ./.github/actions/version
        with:
          repository: ${{ env.REPOSITORY }}
          working_directory: ${{ steps.workspace.outputs.workspace }}
          debug: ${{ env.DEBUG }}
          output_file: versions.json
          branch: ${{ env.BRANCH }}
      - name: 打印输出结果
        run: |
          echo "最新版本: ${{steps.release.outputs.version}}"
          echo "最新版本更新内容: ${{steps.release.outputs.update_content}}"