name: 复制文件
on:
  push:
jobs:
  copy:
    uses: ./.github/workflows/release-part-files.yaml
    secrets:
      srcRepository: m8test/release-to-version
      destRepository: m8test/Test
      srcPath: .github/actions
      destPath: /
      srcToken: ${{ secrets.GITHUB_TOKEN }}
      destToken: ${{ secrets.TEST }}