name: "测试docker workflows是否正确执行"
run-name: "测试docker workflows是否正确执行 | ${{ github.event_name }} 调试模式 - ${{ inputs.debug || github.event_name == 'push' }}"
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 是否开启调试模式
        default: true
      repository:
        type: string
        default: ""
        description: 需要获取信息的仓库，必须为公开类型的仓库

env:
  DEBUG: ${{ inputs.debug || github.event_name == 'push' }}
  REPOSITORY: ${{ inputs.repository || 'kkevsekk1/AutoX' }}

jobs:
  #  jest:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: 下载代码
  #        uses: actions/checkout@v4
  #        with:
  #          repository: m8test/release-to-version
  #      - name: 安装依赖并启动 jest
  #        run: |
  #          npm install
  #          npm run test
  test-docker:
    runs-on: ubuntu-latest
    #    needs:
    #      - jest
    steps:
      - name: 下载仓库代码
        uses: actions/checkout@v4
      - name: 打印环境变量
        id: print_env
        run: |
          echo "workspace=$GITHUB_WORKSPACE" >> "$GITHUB_OUTPUT"
          echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
          echo "GITHUB_ENV=$GITHUB_ENV"
          echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
          echo "GITHUB_PATH=$GITHUB_PATH"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
      - name: 使用 actions
        id: release
        uses: ./.github/actions/version
        with:
          debug: ${{ env.DEBUG }}
          repository: ${{ env.REPOSITORY }}
          output_file: version.json
          working_directory: ${{ steps.print_env.outputs.workspace }}
      - name: 打印输出结果
        run: |
          echo "最新版本: ${{steps.release.outputs.version}}"
          echo "最新版本更新内容: ${{steps.release.outputs.update_content}}"
