name: "测试docker workflows是否正确执行"
run-name: "测试docker workflows是否正确执行 | 调试模式 - ${{ inputs.debug }}"
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 是否开启调试模式
        default: true

env:
  REPOSITORY: m8test/release-to-version@main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}
      - uses: ${{ env.REPOSITORY }}
        with:
          debug: ${{ inputs.debug }}