name: 复制文件
on:
  push:
jobs:
  copy:
    uses: ./.github/workflows/release-part-files.yaml
    with:
      srcRepository: m8test/release-to-version
      destRepository: m8test/Test
      srcPath: .github/actions/
      destPath: ""
      debug: true
    secrets:
      srcToken: ${{ secrets.GITHUB_TOKEN }}
      destToken: ${{ secrets.TEST }}