name: "测试docker workflows是否正确执行"
run-name: "测试docker workflows是否正确执行 | 调试模式 - ${{ inputs.debug || true }}"
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 是否开启调试模式
        default: true
      repository:
        type: string
        default: ""
        description: 需要获取信息的仓库，必须为公开类型的仓库

env:
  DEBUG: ${{ inputs.debug || true }}
  REPOSITORY: ${{ inputs.repository || 'kkevsekk1/AutoX' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 使用 actions
        uses: m8test/release-to-version@main
        with:
          debug: ${{ env.DEBUG }}
          repository: ${{ env.REPOSITORY }}