name: "测试docker workflows是否正确执行"
run-name: "测试docker workflows是否正确执行 | 调试模式 - ${{ inputs.debug }}"
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 是否开启调试模式
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: .
        with:
          debug: ${{ inputs.debug }}